use_frameworks!

platform :ios, '8.0'

target 'EricFramework_Example' do
  pod 'EricFramework', :path => '../'

  target 'EricFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
